### ISSUE TITLE
add pictos for blocks on earlydemo

### ISSUE THREAD

**Issue by clementbonfils** [backbee/DemoBundle#13]
block "article"
![article_jdt](https://cloud.githubusercontent.com/assets/10673014/7346052/ec74b6c6-ecda-11e4-8268-f06d7293bcac.png)

block "paragraph"
![paragraph](https://cloud.githubusercontent.com/assets/10673014/7346084/2c867eac-ecdb-11e4-9fcf-defc9dfbb8c9.png)

Block "linked article"
![offer_list](https://cloud.githubusercontent.com/assets/10673014/7346099/5775085e-ecdb-11e4-9d47-51662da1c9fb.png)

Block "Demo"
![box_demo](https://cloud.githubusercontent.com/assets/10673014/7346183/04da9932-ecdc-11e4-8224-6ab69d483a70.png)

Block "home container"
![bloc_two_columns](https://cloud.githubusercontent.com/assets/10673014/7346209/4428b1b4-ecdc-11e4-8fed-03d4219e8f03.png)

Block "media image"
![image](https://cloud.githubusercontent.com/assets/10673014/7346225/7af166c8-ecdc-11e4-9dbd-2d8301a63405.png)

**Comment by mickaelandrieu** [comment]
:+1: nice addition, ty @clementbonfils
