### ISSUE TITLE
add puzzle image to bundle section

### ISSUE THREAD

**Issue by clementbonfils** [backbee/DemoBundle#14]
![picto-extnd](https://cloud.githubusercontent.com/assets/10673014/7456236/40b26c44-f283-11e4-8dd8-c42ea2738ade.png)

**Comment by eric-chau** [comment]
This should not be in ``demo-bundle`` but ``toolbar-bundle``.

**Comment by eric-chau** [comment]
Resolved in ``backbee/toolbar-bundle`` repository.
