### ISSUE TITLE
Use ApplicationInterface instead of BBApplication

### ISSUE THREAD

**Issue by mickaelandrieu** [backbee/DemoBundle#5]
It's better to have a constraint on a contract (interface) than on implementation(class).

What do you think @eric-chau ?

**Comment by eric-chau** [comment]
Hi @mickaelandrieu, I agree with you but why you mention it in this repository? I can't see any use statement, dependency or extends in ``backbee/demo-bundle``.

**Comment by mickaelandrieu** [comment]
Bad place for this issue, this concerns ``backbee/toolbar-bundle``

**Comment by eric-chau** [comment]
Ok, I close this one.
